-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 08:40:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exam` (
  `id` INT NOT NULL,
  `exam_type` VARCHAR(45) NULL,
  `exam_course` VARCHAR(45) NULL,
  `exam_time` DATETIME NULL,
  `exam_total` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id` INT NOT NULL,
  `student_Fname` VARCHAR(45) NULL,
  `student_Lname` VARCHAR(45) NULL,
  `student_date_of_birth` DATE NULL,
  `student_address` VARCHAR(45) NULL,
  `student_email` VARCHAR(45) NULL,
  `student_phone_number` VARCHAR(11) NULL,
  `professional_id` INT NOT NULL,
  `exam_id` INT NOT NULL,
  PRIMARY KEY (`id`, `professional_id`, `exam_id`),
  INDEX `fk_student_exam_idx` (`exam_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_exam`
    FOREIGN KEY (`exam_id`)
    REFERENCES `mydb`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
