-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 15:38:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`professional1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professional1` (
  `id` INT NOT NULL,
  `prof_Fname` VARCHAR(45) NULL,
  `prof_Lname` VARCHAR(45) NULL,
  `prof_address` VARCHAR(45) NULL,
  `prof_email` VARCHAR(45) NULL,
  `prof_date_of_hire` DATE NULL,
  `prof_phone_number` VARCHAR(11) NULL,
  `prof_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `id` INT NOT NULL,
  `course_name` VARCHAR(45) NULL,
  `course_type` VARCHAR(45) NULL,
  `course_time` DATETIME NULL,
  `professional_id` INT NOT NULL,
  PRIMARY KEY (`id`, `professional_id`),
  INDEX `fk_course_professional_idx` (`professional_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_professional`
    FOREIGN KEY (`professional_id`)
    REFERENCES `mydb`.`professional1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professional` (
  `id` INT NOT NULL,
  `prof_Fname` VARCHAR(45) NULL,
  `prof_Lname` VARCHAR(45) NULL,
  `prof_address` VARCHAR(45) NULL,
  `prof_email` VARCHAR(45) NULL,
  `prof_date_of_hire` DATE NULL,
  `prof_phone_number` VARCHAR(11) NULL,
  `prof_type` VARCHAR(45) NULL,
  `course_id` INT NOT NULL,
  `course_professional_id` INT NOT NULL,
  PRIMARY KEY (`id`, `course_id`, `course_professional_id`),
  INDEX `fk_professional_course1_idx` (`course_id` ASC, `course_professional_id` ASC) VISIBLE,
  CONSTRAINT `fk_professional_course1`
    FOREIGN KEY (`course_id` , `course_professional_id`)
    REFERENCES `mydb`.`course` (`id` , `professional_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exam` (
  `id` INT NOT NULL,
  `exam_type` VARCHAR(45) NULL,
  `exam_course` VARCHAR(45) NULL,
  `exam_time` DATETIME NULL,
  `exam_total` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student2` (
  `idStudent` INT NOT NULL,
  `student_fname` VARCHAR(45) NOT NULL,
  `student_lname` VARCHAR(45) NOT NULL,
  `student_date_of_birth` DATE NOT NULL,
  `student_address` VARCHAR(45) NOT NULL,
  `student_email` VARCHAR(45) NOT NULL,
  `student_phone` VARCHAR(11) NOT NULL,
  `student_date_of_enrollment` DATE NOT NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voucher` (
  `id` INT NOT NULL,
  `voucher_name` VARCHAR(45) NOT NULL,
  `voucher_ type` VARCHAR(45) NOT NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`id`, `Student_idStudent`),
  INDEX `fk_Voucher_Student_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Voucher_Student`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student2` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificate` (
  `id` INT NOT NULL,
  `cert_name` VARCHAR(45) NOT NULL,
  `cert_stu_name` VARCHAR(45) NOT NULL,
  `cert_date` DATE NOT NULL,
  `` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id` INT NOT NULL,
  `student_Fname` VARCHAR(45) NULL,
  `student_Lname` VARCHAR(45) NULL,
  `student_date_of_birth` DATE NULL,
  `student_address` VARCHAR(45) NULL,
  `student_email` VARCHAR(45) NULL,
  `student_phone_number` VARCHAR(11) NULL,
  `professional_id` INT NOT NULL,
  `exam_id` INT NOT NULL,
  `Voucher_id` INT NOT NULL,
  `Voucher_Student_idStudent` INT NOT NULL,
  `Certificate_id` INT NOT NULL,
  PRIMARY KEY (`id`, `professional_id`, `exam_id`, `Voucher_id`, `Voucher_Student_idStudent`, `Certificate_id`),
  INDEX `fk_student_professional_idx` (`professional_id` ASC) VISIBLE,
  INDEX `fk_student_exam1_idx` (`exam_id` ASC) VISIBLE,
  INDEX `fk_student_Voucher1_idx` (`Voucher_id` ASC, `Voucher_Student_idStudent` ASC) VISIBLE,
  INDEX `fk_student_Certificate1_idx` (`Certificate_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_professional`
    FOREIGN KEY (`professional_id`)
    REFERENCES `mydb`.`professional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_exam1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `mydb`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_Voucher1`
    FOREIGN KEY (`Voucher_id` , `Voucher_Student_idStudent`)
    REFERENCES `mydb`.`Voucher` (`id` , `Student_idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_Certificate1`
    FOREIGN KEY (`Certificate_id`)
    REFERENCES `mydb`.`Certificate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student1` (
  `id` INT NOT NULL,
  `student_Fname` VARCHAR(45) NULL,
  `student_Lname` VARCHAR(45) NULL,
  `student_date_of_birth` DATE NULL,
  `student_address` VARCHAR(45) NULL,
  `student_email` VARCHAR(45) NULL,
  `student_phone_number` VARCHAR(11) NULL,
  `professional_id` INT NOT NULL,
  `exam_id` INT NOT NULL,
  PRIMARY KEY (`id`, `professional_id`, `exam_id`),
  INDEX `fk_student_exam_idx` (`exam_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_exam`
    FOREIGN KEY (`exam_id`)
    REFERENCES `mydb`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student3` (
  `id` INT NOT NULL,
  `stud_fname` VARCHAR(45) NOT NULL,
  `stud_lname` VARCHAR(45) NOT NULL,
  `stud_date_of_birth` DATE NOT NULL,
  `stud_address` VARCHAR(45) NOT NULL,
  `stud_email` VARCHAR(45) NOT NULL,
  `stud_phone` VARCHAR(11) NOT NULL,
  `stud_doe` DATE NOT NULL,
  `Certificate_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Certificate_id`),
  INDEX `fk_Student_Certificate_idx` (`Certificate_id` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Certificate`
    FOREIGN KEY (`Certificate_id`)
    REFERENCES `mydb`.`Certificate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`School` (
  `id` INT NOT NULL,
  `school_name` VARCHAR(45) NOT NULL,
  `school_address` VARCHAR(45) NOT NULL,
  `school_phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` INT NOT NULL,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_lname` VARCHAR(45) NOT NULL,
  `employee_date_of_birth` DATE NOT NULL,
  `employee_date_of_time` DATE NOT NULL,
  `employee_address` VARCHAR(45) NOT NULL,
  `employee_phone` VARCHAR(11) NOT NULL,
  `School_id` INT NOT NULL,
  PRIMARY KEY (`id`, `School_id`),
  INDEX `fk_Employee_School_idx` (`School_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_School`
    FOREIGN KEY (`School_id`)
    REFERENCES `mydb`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
